# Generated by Django 2.1.7 on 2020-08-30 08:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('heading', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=100)),
                ('urlfield', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_made', models.CharField(blank=True, max_length=100, null=True)),
                ('investment', models.CharField(blank=True, max_length=10, null=True)),
                ('color_selected', models.CharField(blank=True, max_length=10, null=True)),
                ('num_selected', models.CharField(blank=True, max_length=10, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('result', models.CharField(blank=True, default='unknown', max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('tag', models.CharField(blank=True, default='New', max_length=10, null=True)),
                ('category', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=10)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='NumberGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, max_length=10, null=True)),
                ('total_investment', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('green_investment', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('red_investment', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('purple_investment', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('n_investment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, null=True, size=10)),
                ('result', models.CharField(blank=True, default='unknown', max_length=10, null=True)),
                ('color', models.CharField(blank=True, default='unknown', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paytm_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MERC_UNQ_REF', models.IntegerField(verbose_name='USER ID')),
                ('ORDERID', models.CharField(max_length=30, verbose_name='ORDER ID')),
                ('TXNDATE', models.DateTimeField(default=django.utils.timezone.now, verbose_name='TXN DATE')),
                ('TXNID', models.CharField(max_length=100, verbose_name='TXN ID')),
                ('BANKTXNID', models.CharField(blank=True, max_length=100, null=True, verbose_name='BANK TXN ID')),
                ('BANKNAME', models.CharField(blank=True, max_length=50, null=True, verbose_name='BANK NAME')),
                ('RESPCODE', models.IntegerField(verbose_name='RESP CODE')),
                ('PAYMENTMODE', models.CharField(blank=True, max_length=10, null=True, verbose_name='PAYMENT MODE')),
                ('CURRENCY', models.CharField(blank=True, max_length=4, null=True, verbose_name='CURRENCY')),
                ('GATEWAYNAME', models.CharField(blank=True, max_length=30, null=True, verbose_name='GATEWAY NAME')),
                ('MID', models.CharField(max_length=40)),
                ('RESPMSG', models.TextField(max_length=250, verbose_name='RESP MSG')),
                ('TXNAMOUNT', models.FloatField(verbose_name='TXN AMOUNT')),
                ('STATUS', models.CharField(max_length=12, verbose_name='STATUS')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_payment_order_paytm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('checksum', models.CharField(blank=True, max_length=200, null=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userphoto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('phone_number', models.CharField(default=False, max_length=30)),
                ('total_amount', models.CharField(default='0', max_length=5)),
                ('won', models.CharField(default='0', max_length=5)),
                ('withdrawable', models.CharField(default='0', max_length=5)),
                ('refer_income', models.CharField(default='0', max_length=5)),
                ('ref_code', models.CharField(default=False, max_length=15)),
                ('refer', models.CharField(default=False, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='withdraw_requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default=False, max_length=15)),
                ('UPIID', models.CharField(default=False, max_length=15)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
