# Generated by Django 3.1.4 on 2021-01-22 03:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='TXN DATE')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('added', models.BooleanField(default=False)),
            ],
        ),
    ]
