# Generated by Django 2.2.10 on 2020-09-01 15:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiamondGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, max_length=10, null=True)),
                ('total_investment', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('green_investment', models.FloatField(blank=True, default='0', max_length=10, null=True)),
                ('red_investment', models.FloatField(blank=True, default='0', max_length=10, null=True)),
                ('purple_investment', models.FloatField(blank=True, default='0', max_length=10, null=True)),
                ('n_investment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, null=True, size=10)),
                ('result', models.CharField(blank=True, default='unknown', max_length=10, null=True)),
                ('color', models.CharField(blank=True, default='unknown', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoldGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, max_length=10, null=True)),
                ('total_investment', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('green_investment', models.FloatField(blank=True, default='0', max_length=10, null=True)),
                ('red_investment', models.FloatField(blank=True, default='0', max_length=10, null=True)),
                ('purple_investment', models.FloatField(blank=True, default='0', max_length=10, null=True)),
                ('n_investment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, null=True, size=10)),
                ('result', models.CharField(blank=True, default='unknown', max_length=10, null=True)),
                ('color', models.CharField(blank=True, default='unknown', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, max_length=10, null=True)),
                ('total_investment', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('green_investment', models.FloatField(blank=True, default='0', max_length=10, null=True)),
                ('red_investment', models.FloatField(blank=True, default='0', max_length=10, null=True)),
                ('purple_investment', models.FloatField(blank=True, default='0', max_length=10, null=True)),
                ('n_investment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, null=True, size=10)),
                ('result', models.CharField(blank=True, default='unknown', max_length=10, null=True)),
                ('color', models.CharField(blank=True, default='unknown', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SilverGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, max_length=10, null=True)),
                ('total_investment', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('green_investment', models.FloatField(blank=True, default='0', max_length=10, null=True)),
                ('red_investment', models.FloatField(blank=True, default='0', max_length=10, null=True)),
                ('purple_investment', models.FloatField(blank=True, default='0', max_length=10, null=True)),
                ('n_investment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, null=True, size=10)),
                ('result', models.CharField(blank=True, default='unknown', max_length=10, null=True)),
                ('color', models.CharField(blank=True, default='unknown', max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NumberGame',
        ),
    ]
