# Generated by Django 2.2.10 on 2020-09-03 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diamondgame',
            name='result',
            field=models.CharField(blank=True, default='unknown12', max_length=10, null=True),
        ),       
        migrations.AlterField(
            model_name='goldgame',
            name='result',
            field=models.CharField(blank=True, default='unknown12', max_length=10, null=True),
        ),       
        migrations.AlterField(
            model_name='othergame',
            name='result',
            field=models.CharField(blank=True, default='unknown12', max_length=10, null=True),
        ),        
        migrations.AlterField(
            model_name='silvergame',
            name='result',
            field=models.CharField(blank=True, default='unknown12', max_length=10, null=True),
        ),   
    ]
