# Generated by Django 2.1.7 on 2020-08-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='refer_income',
            field=models.FloatField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_amount',
            field=models.FloatField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='withdrawable',
            field=models.FloatField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='won',
            field=models.FloatField(default='0', max_length=5),
        ),
    ]
