# Generated by Django 2.1.7 on 2020-08-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200830_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbergame',
            name='green_investment',
            field=models.FloatField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='numbergame',
            name='purple_investment',
            field=models.FloatField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='numbergame',
            name='red_investment',
            field=models.FloatField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
