# Generated by Django 2.2.10 on 2020-09-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200901_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='diamondgame',
            name='id_made',
            field=models.CharField(blank=True, default='unknown', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='goldgame',
            name='id_made',
            field=models.CharField(blank=True, default='unknown', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='othergame',
            name='id_made',
            field=models.CharField(blank=True, default='unknown', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='silvergame',
            name='id_made',
            field=models.CharField(blank=True, default='unknown', max_length=20, null=True),
        ),
    ]
