# Generated by Django 2.2.10 on 2020-09-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200902_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='mode',
            field=models.CharField(blank=True, default='unknown', max_length=10, null=True),
        ),
    ]
