# Generated by Django 2.2.10 on 2020-09-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200903_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw_requests',
            name='UPIID',
            field=models.CharField(default=False, max_length=35),
        ),
    ]
