# Generated by Django 2.2.10 on 2020-09-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200903_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='color',
            field=models.CharField(blank=True, default='unknown', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='diamondgame',
            name='color',
            field=models.CharField(blank=True, default='unknown', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='goldgame',
            name='color',
            field=models.CharField(blank=True, default='unknown', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='othergame',
            name='color',
            field=models.CharField(blank=True, default='unknown', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='silvergame',
            name='color',
            field=models.CharField(blank=True, default='unknown', max_length=20, null=True),
        ),
    ]
