# Generated by Django 2.1.7 on 2020-08-31 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200831_0942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
