# Generated by Django 2.1.7 on 2020-08-31 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_carousals'),
    ]

    operations = [        
        migrations.AddField(
            model_name='withdraw_requests',
            name='made_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),        
    ]
