# Generated by Django 2.2.10 on 2020-09-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_rv_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousal1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('heading', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=100)),
                ('urlfield', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Carousal2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('heading', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=100)),
                ('urlfield', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Carousal3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('heading', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=100)),
                ('urlfield', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='carousal',
            name='for_carousal',
        ),
    ]
