# Generated by Django 2.2.10 on 2020-09-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200905_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='redenvelope',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
