# Generated by Django 2.2.10 on 2020-09-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_redenvelope_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='diamondgame',
            name='paid_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goldgame',
            name='paid_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='othergame',
            name='paid_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='silvergame',
            name='paid_users',
            field=models.BooleanField(default=False),
        ),
    ]
