# Generated by Django 2.2.10 on 2020-09-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200905_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diamondgame',
            name='paid_users',
        ),
        migrations.RemoveField(
            model_name='goldgame',
            name='paid_users',
        ),
        migrations.RemoveField(
            model_name='othergame',
            name='paid_users',
        ),
        migrations.RemoveField(
            model_name='silvergame',
            name='paid_users',
        ),
    ]
